plugins {
    id 'java'
    id 'com.diffplug.spotless' version '8.4.0'
}

configurations {
    mockitoAgent
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.mockito:mockito-core:5.23.0'
    // FÜGEN SIE DIESE ZEILE HINZU:
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'

    mockitoAgent('org.mockito:mockito-core:5.23.0') { transitive = false }
}


// use current LTS release: Java 25
java.toolchain.languageVersion = JavaLanguageVersion.of(25)
java.sourceCompatibility = JavaVersion.VERSION_25
java.targetCompatibility = JavaVersion.VERSION_25

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}


test {
    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}"
}

spotless {
    java {
        googleJavaFormat().reflowLongStrings()

        target '**/*.java'
        targetExclude('build/generated-src/**')
    }
}
